# -*- coding: utf-8 -*-
"""100Sports_Image_Classificatio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKvzWqlFaT4y9aVjh_PNIdwASX6v4FWo
"""

from google.colab import drive
drive.mount('/content/drive')

import os

PROJECT_DIR = '/content/drive/MyDrive/sports_classification'

os.makedirs(PROJECT_DIR, exist_ok=True)

print("Project folder created:")
print(PROJECT_DIR)

import os

PROJECT_DIR = '/content/drive/MyDrive/sports_classification'

os.makedirs(PROJECT_DIR, exist_ok=True)

print("Project folder created:")
print(PROJECT_DIR)

import os

print(os.listdir('/content'))

import zipfile
import os

zip_path = '/content/archive.zip'
extract_path = '/content/data'

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

!find /content/data -maxdepth 2 -type d | head -50

!find /content/data -name "sports.csv"

import pandas as pd

df = pd.read_csv('/content/sports.csv')

print(df.head())
print()
print("Number of rows:", len(df))
print("Number of classes:", df['labels'].nunique())

print("Number of classes:", df['labels'].nunique())

print("\nSports classes:")
for i, sport in enumerate(sorted(df['labels'].unique()), 1):
    print(i, sport)

class_counts = df['labels'].value_counts()

print(class_counts)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 25))

class_counts.sort_values().plot(kind='barh')

plt.xlabel('Number of Images')
plt.ylabel('Sports Class')
plt.title('Class Distribution of 100 Sports')

plt.tight_layout()

plt.savefig(
    f'{PROJECT_DIR}/class_distribution.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("Total images:", len(df))
print("Unique image paths:", df['filepaths'].nunique())
print("Number of classes:", df['labels'].nunique())

from PIL import Image
import os

sample_df = df.sample(
    min(200, len(df)),
    random_state=42
)

dimensions = []

for filepath in sample_df['filepaths']:
    full_path = os.path.join('/content/data', filepath)

    try:
        with Image.open(full_path) as img:
            dimensions.append(img.size)
    except Exception as e:
        print("Could not read:", full_path)

from collections import Counter

print(Counter(dimensions).most_common(20))

# Commented out IPython magic to ensure Python compatibility.
# Install ImageHash
# %pip install -q ImageHash

import imagehash
from PIL import Image
import os

hashes = {}
duplicates = []
invalid_files = []

# Check every file
for filepath in df['filepaths']:

    full_path = os.path.join('/content/data', filepath)

    try:
        # Try opening the file as an image
        with Image.open(full_path) as img:
            img.verify()

        # Re-open after verify()
        with Image.open(full_path) as img:
            h = str(imagehash.phash(img))

        # Check duplicate
        if h in hashes:
            duplicates.append(
                (hashes[h], full_path)
            )
        else:
            hashes[h] = full_path

    except Exception as e:
        invalid_files.append({
            "filepath": filepath,
            "error": str(e)
        })

print("=" * 60)
print("DATASET QUALITY CHECK")
print("=" * 60)

print("Total records:", len(df))
print("Valid images:", len(hashes))
print("Invalid/non-image files:", len(invalid_files))
print("Duplicate/near-duplicate pairs:", len(duplicates))

print("\nInvalid files:")
for item in invalid_files:
    print("-", item["filepath"])

print("\nUnique valid images:", len(hashes))

# Remove invalid/non-image files

invalid_paths = [item["filepath"] for item in invalid_files]

df_clean = df[~df['filepaths'].isin(invalid_paths)].copy()

print("=" * 50)
print("CLEANED DATASET")
print("=" * 50)

print("Original records:", len(df))
print("Clean records:", len(df_clean))
print("Removed records:", len(df) - len(df_clean))
print("Number of classes:", df_clean['labels'].nunique())

# Class distribution

class_counts = df_clean['labels'].value_counts().sort_index()

print("Number of classes:", len(class_counts))
print("\nImages in each class:")
print(class_counts)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 25))

class_counts.sort_values().plot(kind='barh')

plt.xlabel("Number of Images")
plt.ylabel("Sports Class")
plt.title("Class Distribution - 100 Sports Image Classification Dataset")

plt.tight_layout()

plt.show()

clean_csv_path = '/content/drive/MyDrive/sports_classification/cleaned_sports.csv'

df_clean.to_csv(clean_csv_path, index=False)

print("Cleaned CSV saved successfully!")
print(clean_csv_path)

from sklearn.model_selection import train_test_split

# 70% Training, 30% Temporary
train_df, temp_df = train_test_split(
    df_clean,
    test_size=0.30,
    stratify=df_clean['labels'],
    random_state=42
)

# Split the remaining 30% into:
# 15% Validation and 15% Testing
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df['labels'],
    random_state=42
)

print("=" * 60)
print("70 / 15 / 15 STRATIFIED DATASET SPLIT")
print("=" * 60)

print("Total images:", len(df_clean))
print("Training images:", len(train_df))
print("Validation images:", len(val_df))
print("Testing images:", len(test_df))

print("\nPercentages:")

total = len(df_clean)

print("Training:", round(len(train_df) / total * 100, 2), "%")
print("Validation:", round(len(val_df) / total * 100, 2), "%")
print("Testing:", round(len(test_df) / total * 100, 2), "%")

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

print("\nClasses:")
print("Train classes:", train_df['labels'].nunique())
print("Validation classes:", val_df['labels'].nunique())
print("Test classes:", test_df['labels'].nunique())

import torch
from torchvision import transforms

# Image size
IMG_SIZE = 224

# Training augmentation
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(
        IMG_SIZE,
        scale=(0.8, 1.0)
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.05
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# Validation preprocessing
val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# Test preprocessing
test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("Transforms created successfully!")

import os
import shutil

# Create the split folders
base_split_path = "/content/split"

os.makedirs(base_split_path, exist_ok=True)


def create_image_split(dataframe, split_name):
    print(f"\nCreating {split_name} split...")

    count = 0

    for _, row in dataframe.iterrows():

        source_path = os.path.join(
            "/content/data",
            row["filepaths"]
        )

        class_name = str(row["labels"])

        destination_dir = os.path.join(
            base_split_path,
            split_name,
            class_name
        )

        os.makedirs(destination_dir, exist_ok=True)

        # Keep original filename
        destination_path = os.path.join(
            destination_dir,
            os.path.basename(row["filepaths"])
        )

        shutil.copy2(source_path, destination_path)

        count += 1

        if count % 1000 == 0:
            print(f"{count} images copied...")

    print(f"{split_name} complete: {count} images")


# Create all three splits
create_image_split(train_df, "train")
create_image_split(val_df, "val")
create_image_split(test_df, "test")

print("\nAll dataset splits created successfully!")

import os

print("Train folder exists:", os.path.exists("/content/split/train"))
print("Validation folder exists:", os.path.exists("/content/split/val"))
print("Test folder exists:", os.path.exists("/content/split/test"))

print("\nNumber of train classes:",
      len(os.listdir("/content/split/train")))

print("Number of validation classes:",
      len(os.listdir("/content/split/val")))

print("Number of test classes:",
      len(os.listdir("/content/split/test")))

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

# Dataset directories
train_path = "/content/split/train"
val_path = "/content/split/val"
test_path = "/content/split/test"

# Create datasets
train_dataset = ImageFolder(
    train_path,
    transform=train_transform
)

val_dataset = ImageFolder(
    val_path,
    transform=val_transform
)

test_dataset = ImageFolder(
    test_path,
    transform=test_transform
)

print("=" * 50)
print("DATASET INFORMATION")
print("=" * 50)

print("Train images:", len(train_dataset))
print("Validation images:", len(val_dataset))
print("Test images:", len(test_dataset))

print("Number of classes:", len(train_dataset.classes))

from pathlib import Path

def count_images(directory):
    extensions = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

    return sum(
        1 for file in Path(directory).rglob("*")
        if file.suffix.lower() in extensions
    )

train_count = count_images(train_path)
valid_count = count_images(val_path)
test_count = count_images(test_path)

total_count = train_count + valid_count + test_count

print("Training images :", train_count)
print("Validation images:", valid_count)
print("Testing images  :", test_count)
print("TOTAL IMAGES    :", total_count)

classes = sorted([
    d.name for d in Path(train_path).iterdir()
    if d.is_dir()
])

NUM_CLASSES = len(classes)

print("Number of classes:", NUM_CLASSES)

for i, cls in enumerate(classes):
    print(i, cls)

def get_class_counts(directory):
    counts = {}

    for cls in classes:
        class_dir = Path(directory) / cls

        if class_dir.exists():
            counts[cls] = count_images(class_dir)
        else:
            counts[cls] = 0

    return counts


train_counts = get_class_counts(train_path)

distribution_df = pd.DataFrame({
    "Class": list(train_counts.keys()),
    "Images": list(train_counts.values())
})

distribution_df = distribution_df.sort_values(
    "Images",
    ascending=False
)

distribution_df.head(20)

os.makedirs("results", exist_ok=True)

distribution_df.to_csv(
    "results/class_distribution.csv",
    index=False
)

plt.figure(figsize=(24, 8))

plt.bar(
    distribution_df["Class"],
    distribution_df["Images"]
)

plt.xticks(rotation=90)
plt.xlabel("Sports Class")
plt.ylabel("Number of Images")
plt.title("Class Distribution - 100 Sports Dataset")

plt.tight_layout()
plt.savefig(
    "results/class_distribution.png",
    dpi=300
)

plt.show()

dimension_counter = Counter()

for split_dir in [train_path, val_path, test_path]:

    for file in Path(split_dir).rglob("*"):

        if file.suffix.lower() in [".jpg", ".jpeg", ".png"]:

            try:
                with Image.open(file) as img:
                    dimension_counter[img.size] += 1

            except:
                pass

dimension_df = pd.DataFrame(
    dimension_counter.items(),
    columns=["Dimensions", "Count"]
)

dimension_df = dimension_df.sort_values(
    "Count",
    ascending=False
)

dimension_df.head(20)

print("Unique image dimensions:")
print(len(dimension_counter))

print("\nMost common dimensions:")
print(dimension_df.head())

import random

fig, axes = plt.subplots(
    4, 5,
    figsize=(15, 12)
)

selected_classes = random.sample(classes, 20)

for ax, cls in zip(axes.flatten(), selected_classes):

    class_dir = Path(train_path) / cls

    image_files = list(class_dir.glob("*.jpg"))

    if len(image_files) == 0:
        image_files = list(class_dir.glob("*"))

    image_path = random.choice(image_files)

    image = Image.open(image_path).convert("RGB")

    ax.imshow(image)
    ax.set_title(cls)
    ax.axis("off")

plt.tight_layout()

plt.savefig(
    "results/sample_images.png",
    dpi=300
)

plt.show()

IMG_SIZE = 224

train_transform = transforms.Compose([

    transforms.Resize((IMG_SIZE, IMG_SIZE)),

    transforms.RandomHorizontalFlip(
        p=0.5
    ),

    transforms.RandomRotation(
        15
    ),

    transforms.RandomResizedCrop(
        IMG_SIZE,
        scale=(0.8, 1.0)
    ),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

IMG_SIZE = 224

train_transform = transforms.Compose([

    transforms.Resize((IMG_SIZE, IMG_SIZE)),

    transforms.RandomHorizontalFlip(
        p=0.5
    ),

    transforms.RandomRotation(
        15
    ),

    transforms.RandomResizedCrop(
        IMG_SIZE,
        scale=(0.8, 1.0)
    ),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

import torchvision.datasets as datasets

train_dataset = datasets.ImageFolder(
    train_path,
    transform=train_transform
)

valid_dataset = datasets.ImageFolder(
    val_path,
    transform=test_transform
)

test_dataset = datasets.ImageFolder(
    test_path,
    transform=test_transform
)

print("Training:", len(train_dataset))
print("Validation:", len(valid_dataset))
print("Testing:", len(test_dataset))

print("Classes:", len(train_dataset.classes))

BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

images, labels = next(iter(train_loader))

print("Batch image shape:", images.shape)
print("Batch label shape:", labels.shape)

import torchvision.models as models
import torch.nn as nn

def create_model(model_name, num_classes):

    if model_name == "ResNet18":

        model = models.resnet18(
            weights=models.ResNet18_Weights.DEFAULT
        )

        model.fc = nn.Linear(
            model.fc.in_features,
            num_classes
        )

    elif model_name == "ResNet50":

        model = models.resnet50(
            weights=models.ResNet50_Weights.DEFAULT
        )

        model.fc = nn.Linear(
            model.fc.in_features,
            num_classes
        )

    elif model_name == "DenseNet121":

        model = models.densenet121(
            weights=models.DenseNet121_Weights.DEFAULT
        )

        model.classifier = nn.Linear(
            model.classifier.in_features,
            num_classes
        )

    elif model_name == "EfficientNetB0":

        model = models.efficientnet_b0(
            weights=models.EfficientNet_B0_Weights.DEFAULT
        )

        model.classifier[1] = nn.Linear(
            model.classifier[1].in_features,
            num_classes
        )

    elif model_name == "MobileNetV3":

        model = models.mobilenet_v3_large(
            weights=models.MobileNet_V3_Large_Weights.DEFAULT
        )

        model.classifier[3] = nn.Linear(
            model.classifier[3].in_features,
            num_classes
        )

    elif model_name == "ConvNeXtTiny":

        model = models.convnext_tiny(
            weights=models.ConvNeXt_Tiny_Weights.DEFAULT
        )

        model.classifier[2] = nn.Linear(
            model.classifier[2].in_features,
            num_classes
        )

    elif model_name == "ViT":

        model = models.vit_b_16(
            weights=models.ViT_B_16_Weights.DEFAULT
        )

        model.heads.head = nn.Linear(
            model.heads.head.in_features,
            num_classes
        )

    else:
        raise ValueError(
            "Unknown model"
        )

    return model

import torchvision.models as models
import torch.nn as nn

def create_model(model_name, num_classes):

    if model_name == "ResNet18":

        model = models.resnet18(
            weights=models.ResNet18_Weights.DEFAULT
        )

        model.fc = nn.Linear(
            model.fc.in_features,
            num_classes
        )

    elif model_name == "ResNet50":

        model = models.resnet50(
            weights=models.ResNet50_Weights.DEFAULT
        )

        model.fc = nn.Linear(
            model.fc.in_features,
            num_classes
        )

    elif model_name == "DenseNet121":

        model = models.densenet121(
            weights=models.DenseNet121_Weights.DEFAULT
        )

        model.classifier = nn.Linear(
            model.classifier.in_features,
            num_classes
        )

    elif model_name == "EfficientNetB0":

        model = models.efficientnet_b0(
            weights=models.EfficientNet_B0_Weights.DEFAULT
        )

        model.classifier[1] = nn.Linear(
            model.classifier[1].in_features,
            num_classes
        )

    elif model_name == "MobileNetV3":

        model = models.mobilenet_v3_large(
            weights=models.MobileNet_V3_Large_Weights.DEFAULT
        )

        model.classifier[3] = nn.Linear(
            model.classifier[3].in_features,
            num_classes
        )

    elif model_name == "ConvNeXtTiny":

        model = models.convnext_tiny(
            weights=models.ConvNeXt_Tiny_Weights.DEFAULT
        )

        model.classifier[2] = nn.Linear(
            model.classifier[2].in_features,
            num_classes
        )

    elif model_name == "ViT":

        model = models.vit_b_16(
            weights=models.ViT_B_16_Weights.DEFAULT
        )

        model.heads.head = nn.Linear(
            model.heads.head.in_features,
            num_classes
        )

    else:
        raise ValueError(
            "Unknown model"
        )

    return model

EPOCHS = 10
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

import torch.optim as optim

def get_optimizer(model):

    return optim.AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY
    )

import torch.nn as nn

criterion = nn.CrossEntropyLoss()

def get_scheduler(optimizer):

    return optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=EPOCHS
    )

def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion
):

    model.train()

    running_loss = 0
    correct = 0
    total = 0

    progress = tqdm(
        loader,
        desc="Training",
        leave=False
    )

    for images, labels in progress:

        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += (
            loss.item() *
            images.size(0)
        )

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy

def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion
):

    model.train()

    running_loss = 0
    correct = 0
    total = 0

    progress = tqdm(
        loader,
        desc="Training",
        leave=False
    )

    for images, labels in progress:

        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += (
            loss.item() *
            images.size(0)
        )

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy

def validate(
    model,
    loader,
    criterion
):

    model.eval()

    running_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in tqdm(
            loader,
            desc="Validation",
            leave=False
        ):

            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            outputs = model(images)

            loss = criterion(
                outputs,
                labels
            )

            running_loss += (
                loss.item() *
                images.size(0)
            )

            _, predicted = torch.max(
                outputs,
                1
            )

            total += labels.size(0)

            correct += (
                predicted == labels
            ).sum().item()

    loss = running_loss / total
    accuracy = correct / total

    return loss, accuracy

def train_model(model_name):

    print("\n" + "="*60)
    print("TRAINING:", model_name)
    print("="*60)

    model = create_model(
        model_name,
        NUM_CLASSES
    )

    model = model.to(DEVICE)

    optimizer = get_optimizer(model)

    scheduler = get_scheduler(
        optimizer
    )

    best_val_accuracy = 0

    history = {
        "train_loss": [],
        "train_accuracy": [],
        "val_loss": [],
        "val_accuracy": []
    }

    os.makedirs(
        "results/checkpoints",
        exist_ok=True
    )

    for epoch in range(EPOCHS):

        print(
            f"\nEpoch {epoch+1}/{EPOCHS}"
        )

        train_loss, train_acc = train_one_epoch(
            model,
            train_loader,
            optimizer,
            criterion
        )

        val_loss, val_acc = validate(
            model,
            valid_loader,
            criterion
        )

        scheduler.step()

        history["train_loss"].append(
            train_loss
        )

        history["train_accuracy"].append(
            train_acc
        )

        history["val_loss"].append(
            val_loss
        )

        history["val_accuracy"].append(
            val_acc
        )

        print(
            f"Train Loss: {train_loss:.4f}"
        )

        print(
            f"Train Accuracy: {train_acc:.4f}"
        )

        print(
            f"Val Loss: {val_loss:.4f}"
        )

        print(
            f"Val Accuracy: {val_acc:.4f}"
        )

        if val_acc > best_val_accuracy:

            best_val_accuracy = val_acc

            torch.save(
                model.state_dict(),
                f"results/checkpoints/{model_name}_best.pth"
            )

            print("Best model saved.")

    return model, history

import json
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# -----------------------------
# Training configuration
# -----------------------------
EPOCHS = 10
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

# Make sure results folder exists
import os
os.makedirs("results", exist_ok=True)
os.makedirs("results/checkpoints", exist_ok=True)


# -----------------------------
# Optimizer
# -----------------------------
def get_optimizer(model):

    return optim.AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY
    )


# -----------------------------
# Scheduler
# -----------------------------
def get_scheduler(optimizer):

    return optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=EPOCHS
    )


# -----------------------------
# Loss
# -----------------------------
criterion = nn.CrossEntropyLoss()


# -----------------------------
# Train one epoch
# -----------------------------
def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion
):

    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += (
            loss.item() * images.size(0)
        )

        predictions = outputs.argmax(
            dim=1
        )

        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy


# -----------------------------
# Validation
# -----------------------------
def validate(
    model,
    loader,
    criterion
):

    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            outputs = model(images)

            loss = criterion(
                outputs,
                labels
            )

            running_loss += (
                loss.item() * images.size(0)
            )

            predictions = outputs.argmax(
                dim=1
            )

            correct += (
                predictions == labels
            ).sum().item()

            total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy


# -----------------------------
# Train model
# -----------------------------
def train_model(model_name):

    print("=" * 60)
    print(f"TRAINING: {model_name}")
    print("=" * 60)

    model = create_model(
        model_name,
        NUM_CLASSES
    )

    model = model.to(DEVICE)

    optimizer = get_optimizer(model)

    scheduler = get_scheduler(
        optimizer
    )

    best_val_accuracy = 0.0

    history = {
        "train_loss": [],
        "train_accuracy": [],
        "val_loss": [],
        "val_accuracy": []
    }

    for epoch in range(EPOCHS):

        print(
            f"\nEpoch {epoch + 1}/{EPOCHS}"
        )

        train_loss, train_acc = train_one_epoch(
            model,
            train_loader,
            optimizer,
            criterion
        )

        val_loss, val_acc = validate(
            model,
            valid_loader,
            criterion
        )

        scheduler.step()

        history["train_loss"].append(
            train_loss
        )

        history["train_accuracy"].append(
            train_acc
        )

        history["val_loss"].append(
            val_loss
        )

        history["val_accuracy"].append(
            val_acc
        )

        print(
            f"Train Loss     : {train_loss:.4f}"
        )

        print(
            f"Train Accuracy : {train_acc * 100:.2f}%"
        )

        print(
            f"Val Loss       : {val_loss:.4f}"
        )

        print(
            f"Val Accuracy   : {val_acc * 100:.2f}%"
        )

        # Save best model
        if val_acc > best_val_accuracy:

            best_val_accuracy = val_acc

            torch.save(
                model.state_dict(),
                f"results/checkpoints/"
                f"{model_name}_best.pth"
            )

            print(
                "✓ Best model saved"
            )

    return model, history


# -----------------------------
# Train selected models
# -----------------------------
all_histories = {}

for model_name in MODEL_NAMES:

    model, history = train_model(
        model_name
    )

    all_histories[
        model_name
    ] = history

    # Save history
    with open(
        f"results/{model_name}_history.json",
        "w"
    ) as f:

        json.dump(
            history,
            f,
            indent=4
        )

    del model

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


# -----------------------------
# Plot accuracy
# -----------------------------
for model_name in MODEL_NAMES:

    history = all_histories[
        model_name
    ]

    plt.figure(
        figsize=(10, 6)
    )

    plt.plot(
        history["train_accuracy"],
        label="Training Accuracy"
    )

    plt.plot(
        history["val_accuracy"],
        label="Validation Accuracy"
    )

    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")

    plt.title(
        f"{model_name} - Accuracy"
    )

    plt.legend()
    plt.grid()

    plt.tight_layout()

    plt.savefig(
        f"results/"
        f"{model_name}_accuracy_curve.png",
        dpi=300
    )

    plt.show()

MODEL_NAMES = ['ResNet18']

MODEL_NAMES = [
    'ResNet18',
    'ResNet50',
    'DenseNet121',
    'EfficientNetB0',
    'MobileNetV3',
    'ConvNeXtTiny',
    'ViT'
]

import torch.optim as optim

import pandas as pd
import torch
import torch.nn as nn
import time
import os
from sklearn.metrics import f1_score

# Assuming create_model, validate, DEVICE, NUM_CLASSES, test_loader, criterion are already defined and available

def count_parameters(model):
    """Counts the total number of trainable parameters in a model."""
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def evaluate_model_metrics(model_name):
    print(f"Evaluating {model_name}...")
    try:
        # Load the best model checkpoint
        checkpoint_path = f"results/checkpoints/{model_name}_best.pth"
        if not os.path.exists(checkpoint_path):
            print(f"Warning: Checkpoint not found for {model_name}. Skipping evaluation.")
            return None

        model = create_model(model_name, NUM_CLASSES)
        model.load_state_dict(torch.load(checkpoint_path, map_location=DEVICE))
        model = model.to(DEVICE)
        model.eval()

        # Evaluate on test set
        test_loss, test_accuracy = validate(model, test_loader, criterion)

        # Calculate inference time
        start_time = time.time()
        with torch.no_grad():
            for images, _ in test_loader:
                images = images.to(DEVICE)
                _ = model(images)
        end_time = time.time()
        inference_time_per_image_ms = (end_time - start_time) / len(test_loader.dataset) * 1000

        # Count parameters
        total_parameters = count_parameters(model)

        # Calculate F1-score (macro average)
        all_preds = []
        all_labels = []
        with torch.no_grad():
            for images, labels in test_loader:
                images = images.to(DEVICE)
                outputs = model(images)
                _, predicted = torch.max(outputs, 1)
                all_preds.extend(predicted.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        f1 = f1_score(all_labels, all_preds, average='macro')

        return {
            "Model": model_name,
            "Accuracy": test_accuracy,
            "F1-Score": f1,
            "Inference Time (ms)": inference_time_per_image_ms,
            "Total Parameters": total_parameters
        }

    except Exception as e:
        print(f"Error evaluating {model_name}: {e}")
        return None

# Collect results for all models
all_model_results = []
for model_name in MODEL_NAMES:
    result = evaluate_model_metrics(model_name)
    if result:
        all_model_results.append(result)

# Create DataFrame and save
if all_model_results:
    final_comparison = pd.DataFrame(all_model_results)
    final_comparison.to_csv("results/final_model_comparison.csv", index=False)
    print("\n'results/final_model_comparison.csv' created successfully!")
    print(final_comparison)
else:
    print("\nNo models were successfully evaluated to create 'results/final_model_comparison.csv'.")
    final_comparison = pd.DataFrame() # Create an empty DataFrame to avoid NameError below

# Original discussion block (now conditional)
if not final_comparison.empty:
    best_accuracy_row = (
        final_comparison
        .sort_values(
            "Accuracy",
            ascending=False
        )
        .iloc[0]
    )

    best_f1_row = (
        final_comparison
        .sort_values(
            "F1-Score",
            ascending=False
        )
        .iloc[0]
    )

    fastest_row = (
        final_comparison
        .sort_values(
            "Inference Time (ms)"
        )
        .iloc[0]
    )

    smallest_row = (
        final_comparison
        .sort_values(
            "Total Parameters"
        )
        .iloc[0]
    )

    print(
        f"""
DISCUSSION

Seven deep-learning architectures were evaluated on the
100 Sports Image Classification dataset using the same
training and testing protocol.

The highest test accuracy was achieved by
{best_accuracy_row['Model']}, with an accuracy of
{best_accuracy_row['Accuracy']:.4f}.

The highest macro F1-score was achieved by
{best_f1_row['Model']}, with an F1-score of
{best_f1_row['F1-Score']:.4f}.

The fastest inference time was obtained by
{fastest_row['Model']}, with an average inference time of
{fastest_row['Inference Time (ms)']:.2f} ms per image.

The smallest model in terms of parameter count was
{smallest_row['Model']}, containing approximately
{smallest_row['Total Parameters']/1e6:.2f} million parameters.

The results demonstrate that model selection involves a
trade-off between classification performance and
computational efficiency.

The XAI analysis using Grad-CAM provides visual evidence
of the image regions that influence CNN predictions.
SHAP provides an additional feature-attribution perspective,
allowing the predictions to be examined using a different
explainability methodology.
"""
    )
else:
    print("\nCannot generate discussion: 'final_model_comparison.csv' could not be created or is empty. Please ensure all models are trained and their checkpoints are saved.")